name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Build the Java application
      - name: Build with Maven
        run: mvn install -f Java-Proect_sonarQube/MyWebApp/pom.xml

      # Run tests
      - name: Run tests
        run: mvn -B test

      # Perform code quality check (example using SpotBugs)
      - name: Code quality check
        run: mvn -B spotbugs:check

      # Generate report (example using JaCoCo for code coverage)
      - name: Generate coverage report
        run: mvn -B jacoco:report

      # Publish report
      - name: Publish report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/site/jacoco/index.html
